config: Add "recombinant" clade definition
Our automated model runs failed on 2023-10-30¹ with AssertionError raised
by `modify-lineage-colours-and-order.py`

```
AssertionError: Missing definitions for the following clades: recombinant
```

¹ https://bedfordlab.slack.com/archives/C03BY4MPNCS/p1698733327193829