scripts/run-renewal-model: Update to `model.gen_v_names`
Ran into error in test run:
```
AttributeError: 'RenewalModel' object has no attribute 'v_names'
```

Updating the script to use `model.gen_v_names` according to the
RenewalModel class defined in evofr.¹

¹ https://github.com/blab/evofr/blob/fa6fd74931050149d2e961f705b2c84204b654e4/evofr/models/renewal_model/renewal_model.py#L28